---
title: "Pre-Testing"
author: "Brantly Callaway and Pedro H.C. Sant&apos;Anna"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pre-Testing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Pre-Testing

Another very appealing feature of many DID applications with multiple periods is that the researcher can pre-test the parallel trends assumptions.

The idea here is simple: although one can not test whether parallel trends itself holds, one can check if it holds in periods before treated units actually become treated.

Importantly, this is just a pre-test; it is different from an actual test.  Whether or not the parallel trends assumption holds in pre-treatment periods does not actually tell you if it holds in the current period (and this is when you need it to hold!).  It is certainly possible for the identifying assumptions to hold in previous periods but not hold in current periods; it is also possible for identifying assumptions to be violated in previous periods but for them to hold in current periods.  That being said, the right way to think about a pre-test is as (potentially strong) piece of evidence on the validity of the DID design in a particular application.

## Common Approaches to Pre-Testing in Applications

By far the most common approach to pre-testing in applications is to run an **event-study regression**.

### Pitfalls with Event Study Regressions



## Pre-Treatment Group-Time Average Treatment Effects



## Conditional Moment Tests



## References

* Abraham, Sarah, and Liyang Sun. "Estimating dynamic treatment effects in event studies with heterogeneous treatment effects." Available at SSRN 3158747 (2018).

* Callaway, Brantly, and Pedro HC Sant'Anna. "Difference-in-differences with multiple time periods." Available at SSRN 3148250 (2019).