library(testthat)

# ===========================================================================
# Validation of the .edid_aks_core interpolation against the AUTHORS' OWN
# published usage: the MissAdapt README vignette (Armstrong, Kline & Sun,
# Econometrica 2025; https://github.com/lsun20/MissAdapt, commit 98d823a).
#
# The vignette feeds the Table-3 inputs of de Chaisemartin & D'Haultfoeuille
# (2020, AER; the Gentzkow et al. 2011 newspaper application):
#     YR  = 0.0026, VR = 0.0009^2   (restricted estimate, squared SE)
#     YU  = 0.0043, VU = 0.0014^2   (unrestricted estimate, squared SE)
#     VUR = 0.7236 * sqrt(VR * VU)  (their replication-data covariance)
# and reports (README, "A vignette for example usage"):
#     tO ~ -1.75, corr ~ -0.77, and the results table (estimates x 100):
#     YU = 0.43, YR = 0.26, Adaptive = 0.36, Soft-threshold = 0.36,
#     soft-threshold value = 0.64.
#
# These tests go through the interpolation core directly (NOT through edid
# fits), pinning our lookup-table conversion + spline interpolation to the
# published example. Full-precision reference values were generated by
# running the authors' own R/calculate_adaptive_estimates.R (at commit
# 98d823a) against the same lookup tables; the README-precision assertions
# (round to the printed digits) are kept separate so a failure says clearly
# whether we broke agreement with the PUBLISHED numbers or only with the
# higher-precision reference run.
# ===========================================================================

test_that("adaptive core reproduces the MissAdapt README vignette (dCdH 2020 Table 3)", {
  YR <- 0.0026; VR <- 0.0009^2
  YU <- 0.0043; VU <- 0.0014^2
  VUR <- 0.7236 * sqrt(VR * VU)

  r <- .edid_aks_core(YR = YR, VR = VR, YU = YU, VU = VU, VUR = VUR)

  # --- README-precision (the published numbers, at the precision printed) ---
  expect_equal(round(r$tO, 2),   -1.75)
  expect_equal(round(r$corr, 2), -0.77)
  expect_equal(round(100 * YU, 2),            0.43)
  expect_equal(round(100 * YR, 2),            0.26)
  expect_equal(round(100 * r$adaptive, 2),    0.36)   # README "Adaptive"
  expect_equal(round(100 * r$adaptive_st, 2), 0.36)   # README "Soft-threshold"
  expect_equal(round(r$soft_threshold, 2),    0.64)   # README "Threshold" row

  # --- full precision vs the authors' calculate_adaptive_estimates.R run ---
  expect_equal(r$tO,           -1.747359190350, tolerance = 1e-9)
  expect_equal(r$corr,         -0.769619216098, tolerance = 1e-9)
  expect_equal(r$GMM,           0.002417278306, tolerance = 1e-12)
  expect_equal(r$se_GMM,        0.000893904399, tolerance = 1e-12)
  expect_equal(r$adaptive,      0.003565247561, tolerance = 1e-9)
  expect_equal(r$adaptive_st,   0.003606845869, tolerance = 1e-9)
  expect_equal(r$adaptive_ht,   0.0043,         tolerance = 1e-12)  # |tO| > ht -> YU
  expect_equal(r$soft_threshold, 0.643318258399, tolerance = 1e-9)
  expect_equal(r$hard_threshold, 1.425635425096, tolerance = 1e-9)
  expect_equal(r$erm,            0.003835504811, tolerance = 1e-12)
  expect_equal(r$adaptive_erm,   0.003619470644, tolerance = 1e-9)
  expect_equal(r$erm_lambda,     1.728372250795, tolerance = 1e-9)
})

test_that("adaptive core reproduces the vignette's efficient-restricted variant (VUR = VR)", {
  # The authors' example.R actually ships with `VUR <- VR; # if we treat YR
  # as efficient` active -- the same convention as assume_efficient = TRUE.
  # Reference values from running their code with VUR = VR.
  YR <- 0.0026; VR <- 0.0009^2
  YU <- 0.0043; VU <- 0.0014^2

  r_explicit <- .edid_aks_core(YR = YR, VR = VR, YU = YU, VU = VU, VUR = VR)
  expect_equal(r_explicit$GMM,      0.0026,         tolerance = 1e-15)  # = YR
  expect_equal(r_explicit$corr,    -0.765986092483, tolerance = 1e-9)   # -sqrt(1 - VR/VU)
  expect_equal(r_explicit$corr,    -sqrt(1 - VR / VU), tolerance = 1e-12)
  expect_equal(r_explicit$adaptive, 0.003520991511, tolerance = 1e-9)
  expect_equal(r_explicit$adaptive_st, 0.003613472662, tolerance = 1e-9)

  # assume_efficient = TRUE must impose VUR = VR regardless of the VUR passed,
  # with the GMM = YR / V_GMM = VR identities exact (not just approximate).
  r_assumed <- .edid_aks_core(YR = YR, VR = VR, YU = YU, VU = VU,
                              VUR = 0.7236 * sqrt(VR * VU),  # ignored
                              assume_efficient = TRUE)
  expect_identical(r_assumed$GMM,   YR)
  expect_identical(r_assumed$V_GMM, VR)
  expect_identical(r_assumed$VUR,   VR)
  expect_true(r_assumed$assume_efficient)
  # identical interpolation path as the explicit VUR = VR call
  expect_equal(r_assumed$adaptive,    r_explicit$adaptive,    tolerance = 1e-12)
  expect_equal(r_assumed$adaptive_st, r_explicit$adaptive_st, tolerance = 1e-12)
  expect_equal(r_assumed$tO,          r_explicit$tO,          tolerance = 1e-12)
  expect_equal(r_assumed$rho_aks_sq,  1 - VR / VU,            tolerance = 1e-12)
})
