# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkTreatmentUniqueness <- function(dta, idname, treatName) {
    invisible(.Call('_did_checkTreatmentUniqueness', PACKAGE = 'did', dta, idname, treatName))
}

checkWeightsUniqueness <- function(dta, idname) {
    invisible(.Call('_did_checkWeightsUniqueness', PACKAGE = 'did', dta, idname))
}

