name: R-CMD-check for Specific Commit

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to run the workflow for'
        required: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.commit_sha }}

    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        http-user-agent: ${{ matrix.config.http-user-agent }}
        use-public-rspm: true

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev libcurl4-openssl-dev

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-${{ matrix.config.r }}-
          ${{ runner.os }}-r-

    - name: Install R package dependencies
      run: R -e "install.packages('devtools'); devtools::install_deps(dependencies = TRUE)"

    - name: Run R CMD check
      uses: r-lib/actions/check-r-package@v2
