name: R-Package-Test for Specific Commit or Branch

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g., person/repo) to run the workflow for'
        required: true
      branch:
        description: 'Branch name to run the workflow for (leave empty if using commit SHA)'
        required: false
        default: ''
      commit_sha:
        description: 'Commit SHA to run the workflow for (leave empty if using branch)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repo_name }}  # Use the input for repository name
        ref: ${{ github.event.inputs.commit_sha || github.event.inputs.branch }}  # Use commit SHA if provided, else branch
        fetch-depth: 0  # Fetch all history to ensure the commit is found

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev libcurl4-openssl-dev

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-
      
    - name: Install R package dependencies
      run: R -e "install.packages('devtools'); devtools::install_deps(dependencies = TRUE)"

    - name: Run tests
      run: R -e "devtools::test()"
